- name: Mettre à jour les paquets de sécurité
  hosts: all
  become: yes
  tasks:
    - name: Ensure unattended-upgrades is installed
      apt:
        name: unattended-upgrades
        state: present

    - name: Configure unattended-upgrades to allow only security updates
      copy:
        dest: /etc/apt/apt.conf.d/50unattended-upgrades
        content: |
          Unattended-Upgrade::Allowed-Origins {
            "${distro_id}:${distro_codename}-security";
          };
          Unattended-Upgrade::Automatic-Reboot "false";
      when: ansible_os_family == "Debian"

    - name: Run unattended-upgrades
      command: unattended-upgrades -d
      when: ansible_os_family == "Debian"

    - name: Check if reboot is required
      stat:
        path: /var/run/reboot-required
      register: reboot_required

    - name: Reboot the server if needed
      reboot:
        msg: "Rebooting after security updates"
      when: reboot_required.stat.exists
