- name: Mettre à jour les paquets de sécurité
  hosts: all
  become: yes
  tasks:
    - name: Ensure unattended-upgrades is installed
      apt:
        name: unattended-upgrades
        state: present

    - name: Configure unattended-upgrades to allow only security updates
      copy:
        dest: /etc/apt/apt.conf.d/50unattended-upgrades
        content: |
          Unattended-Upgrade::Allowed-Origins {
            "{{ ansible_facts['distribution'] }}:{{ ansible_facts['distribution_release'] }}-security";
          };
          Unattended-Upgrade::Automatic-Reboot "false";
      when: ansible_facts['os_family'] == "Debian"

    - name: Validate apt sources
      command: cat /etc/apt/sources.list
      register: apt_sources
      changed_when: false

    - name: Run unattended-upgrades
      command: unattended-upgrades -d
      register: upgrade_output
      changed_when: false
      when: ansible_facts['os_family'] == "Debian"

    - name: Log upgrade output
      copy:
        dest: /var/log/unattended-upgrades-ansible.log
        content: "{{ upgrade_output.stdout }}"

    - name: Check if reboot is required
      stat:
        path: /var/run/reboot-required
      register: reboot_required

    - name: Reboot the server if needed
      reboot:
        msg: "Rebooting after security updates"
      when: reboot_required.stat.exists
